openapi: 3.0.0
info:
  description: Management API to query data in Moesif. You can use the management API to export data for custom reports or to build custom dashboards.
  contact:
  - email: support@moesif.com
  - email: support@moesif.com
  termsOfService: https://www.moesif.com/terms
  version: '1'
  title: Management Applications Product Catalog API
servers:
- url: https://api.moesif.com/v1
  description: Management API V1
- url: https://api.moesif.com/v1
  description: Management API V1
tags:
- name: Product Catalog
paths:
  /~/billing/catalog/plans:
    post:
      security:
      - managementAPIToken:
        - create:plans
      tags:
      - Product Catalog
      operationId: createMoesifPlan
      summary: Create a new Moesif Plan
    get:
      security:
      - managementAPIToken:
        - read:plans
      tags:
      - Product Catalog
      operationId: listMoesifPlans
      summary: List all Moesif Plans
  /~/billing/catalog/plans/{id}:
    get:
      security:
      - managementAPIToken:
        - read:plans
      description: Get the Moesif Plan for authenticated users
      tags:
      - Product Catalog
      operationId: getMoesifPlan
      summary: Get a Moesif Plan
    delete:
      security:
      - managementAPIToken:
        - delete:plans
      tags:
      - Product Catalog
      operationId: deleteMoesifPlan
      summary: Delete a Moesif Plan
    put:
      security:
      - managementAPIToken:
        - update:plans
      tags:
      - Product Catalog
      operationId: updateMoesifPlan
      summary: Update a Moesif Plan
  /~/billing/catalog/prices:
    post:
      security:
      - managementAPIToken:
        - create:prices
      tags:
      - Product Catalog
      operationId: createMoesifPrice
      summary: Create a new Moesif Price
    get:
      security:
      - managementAPIToken:
        - read:prices
      tags:
      - Product Catalog
      operationId: listMoesifPrices
      summary: List all Moesif Prices for a specific Plan
  /~/billing/catalog/prices/{id}:
    get:
      security:
      - managementAPIToken:
        - read:prices
      description: Get the Moesif Price for a specific Plan for authenticated users
      tags:
      - Product Catalog
      operationId: getMoesifPrice
      summary: Get a Moesif Price
    delete:
      security:
      - managementAPIToken:
        - delete:prices
      tags:
      - Product Catalog
      operationId: deleteMoesifPrice
      summary: Delete a Moesif Price
    put:
      security:
      - managementAPIToken:
        - update:prices
      tags:
      - Product Catalog
      operationId: updateMoesifPrice
      summary: Update a Moesif Price
components:
  securitySchemes:
    managementAPIToken:
      type: oauth2
      description: "Your Management API token must be added to the request _Authorization_ header using the following format:\n\n `Authorization: Bearer YOUR_MANAGEMENT_API_KEY`"
      flows:
        password:
          tokenUrl: https://api.moesif.com/v1/:orgId/oauth/access_tokens
          scopes:
            create:encrypted_keys: Create encrypted Keys for the Moesif secure proxy
            delete:dashboards: Delete existing dashboards
            update:dashboards: Update existing dashboards
            create:dashboards: Create a new team dashboard that can be shared
            read:public_workspaces: Read public workspaces/shared links
            read:virtual_eventtypes: Read existing virtual events/tags
            update:companies: Update existing companies and associated company metadata
            create:companies: Create new companies and associated company metadata
            create:reports: Create a new report such as SmartDiff
            delete:workspaces: Delete existing workspaces
            create:workspaces: Create a new workspace/chart that can be shared
            read:workspaces: Read existing workspaces
            update:virtual_eventtypes: Update existing virtual events/tags
            create:cohorts: Save new customer cohorts
            delete:encrypted_keys: Delete encrypted Keys for the Moesif secure proxy
            read:dashboards: Read existing dashboards
            read:events: Read/query events and associated event metadata
            create:events: Create new events and associated event metadata
            read:cohorts: Read previously saved customer cohorts
            read:encrypted_keys: Read encrypted Keys for the Moesif secure proxy
            update:apps: Update an existing application
            update:encrypted_keys: Update encrypted Keys for the Moesif secure proxy
            update:organizations: Update an existing application
            create:access_tokens: Create new tokens to access the Management API or Collector API
            create:users: Create new users and associated user metadata
            create:apps: Create a new application/project under the organization
            update:workspaces: Update existing workspaces
            delete:cohorts: Delete previously saved customer cohorts
            read:users: Read/query users and associated user metadata
            delete:virtual_eventtypes: Delete existing virtual events/tags
            read:reports: Read reports such as SmartDiff
            delete:reports: Delete existing reports such as SmartDiff
            update:users: Update existing users and associated user metadata
            update:cohorts: Update previously saved customer cohorts
            read:companies: Read/query companies and associated company metadata
            create:virtual_eventtypes: Create virtual events/tags
            delete:apps: Delete an existing application
            delete:companies: Delete existing companies and associated company metadata
            read:apps: Read the organization's applications
            create:eth_abi: Create/upload new Ethereum ABI Entries
            delete:users: Delete existing users and associated user metadata